version: '2'
services: 
  app:
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
      args:
        APP_ENV: development
        BUILD_ENV: dev
    command: bash -c "npm install && npm start"
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app:rw
      - ./node_modules/:/usr/src/app/node_modules/:rw
      